import { getServerSession } from 'next-auth'
import { SessionProvider } from '../../components/SessionProvider'
import './globals.css'
import { Poppins } from 'next/font/google'
import ClientProvider from '../../components/ClientProvider'
import Navbar from '../../components/navbar'
import { ToastContainer } from 'react-toastify'

import 'react-toastify/dist/ReactToastify.css'
import LandingPage from './landingPage'
import { authOptions } from './api/auth/[...nextauth]/route'

const poppins = Poppins({ weight: '400', subsets: ['latin'] })

export const metadata = {
	title: 'Savannah App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const session = await getServerSession(authOptions) 

	return (
		<html lang='en'>
			<body className={poppins.className}>
				{/* session setup */}
				<SessionProvider session={session}>
					{/* navbar */}
					<Navbar />
					{/* content page */}
					{!session ? <LandingPage /> : <>{children}</>}
					<ToastContainer />
				</SessionProvider>
			</body>
		</html>
	)
}
