import { getServerSession } from "next-auth";
import { SessionProvider } from "../../components/SessionProvider";
import "./globals.css";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { Poppins } from "next/font/google";
import ClientProvider from "../../components/ClientProvider";
import Navbar from "../../components/navbar";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Savannah App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SessionProvider session={session}>
          <Navbar />

          {/* ClientProvider - Notification */}
          <ClientProvider />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
